### PR TITLE
support windows

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by arbarlow** [comment]
Hi @mattn, I'll take a look a the tests and get this merged, thanks!

**Comment by mattn** [comment]
Currently, there is remaining issue about coloring on Windows which doesn't output colors using logrus on server app.

**Comment by arbarlow** [comment]
I reworked the `file.Close` a bit, but merged the windows colouring! Thanks

**Comment by mattn** [comment]
Thank you.

**Pull request merged**
