### PR TITLE
minor update to subscribe code

### PR DESCRIPTION
**Pull request by nadilas**

### CODE REVIEW

**Comment by arbarlow** [comment]
Thanks @nadilas, this readme is well out of date! As I work towards a new version and pubsub version I'll update both to be simpler too

**Comment by nadilas** [comment]
@arbarlow No problem :) I really like your approach. I am starting with a service discovery layer, should I make a PR out of it once ready?

**Comment by arbarlow** [comment]
absolutely, I assume you need service discovery that is more than just DNS? (consul, zookeeper)

**Comment by nadilas** [comment]
I'm thinking consul to start with

**Pull request merged**
